name: "assembly-stats"
description: Generates report of summary statistics for a genome assembly, including
  - "filename: Assembly name"
  - "total_length: Assembly length"
  - "number: Count of scaffolds/contigs"
  - "mean_length: Average scaffold length"
  - "longest: Length of longest scaffold/contig"
  - "shortest: Length of shortest scaffold/contig"
  - "N_count: Count of undetermined nucleotide bases ('N's)"
  - "N50"
  - "N50N"
  - "N70"
  - "N70N"
  - "N90"
  - "N90N"
authors:
  - Pathogen Informatics, Wellcome Sanger Institute (assembly-stats tool) - https://github.com/sanger-pathogens
  - Max Cummins (Snakemake wrapper [unaffiliated with Wellcome Sanger Institute])
input:
  - Genomic assembly (fasta format)
output:
  - Assembly statistics (format of your choosing, default = tab-delimited)
notes: |
  * The `extra` param allows for additional program arguments.
  * For more inforamtion see https://github.com/sanger-pathogens/assembly-stats